version: '3.8'

services:
  db:
    image: mongo
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db

  app:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
