version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  urlshortener:
    build: .
    container_name: urlshortener_container
    restart: always
    ports:
      - "80:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/urlshortener
    depends_on:
      - mongodb

volumes:
  mongo_data:
